# Generated by Django 3.0.5 on 2020-04-27 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200423_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_date_hapend',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
