# Generated by Django 3.0.5 on 2020-04-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_card_date_hapend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_images',
            field=models.ImageField(blank=True, null=True, upload_to='card_images'),
        ),
    ]
